### PR TITLE
Implement Plus Codes

### PR DESCRIPTION
**Pull request by aazuspan**
Implements #23 by adding the following features: 

- ee.Geometry constructors from full and short Plus Codes
- Methods to extract Plus Codes from ee.Geometry and ee.Feature objects

### CODE REVIEW

**Comment by davemlz** [comment]
Hi, @aazuspan!

Sorry for the late response and thank you for the PR! I hope to start reviewing it today and let you know how things are going!

**Comment by davemlz** [comment]
Hi, @aazuspan. Question here, is it required some sort of authentication for using openlocationcode?

**Comment by aazuspan** [comment]
Hi @davemlz, the openlocationcode package doesn't require any authentication. It just runs a pretty simple algorithm to convert Plus Codes to longitude/latitude coordinates and vice versa, totally offline.

**Comment by davemlz** [comment]
Hi, @aazuspan!

I don't know what's happening with the automatic testing. But it seems that it is required to have your own EE token in the forked repository. Please do the following:

In the repository, please go to Settings > Secrets > New repository secret.

In that window, please fill the Name of the secret as EE_TOKEN, and in the Value, please check your EE credentials file. It is usually in the users root of your local machine: "./.config/earthengine/credentials". In that file you will find the `refresh_token` and its value; please copy and paste that value (without the quotation marks) in the repository secret.

Then, please update your branch since I have modified some files, I think there are not conflicts, but just to be sure! Then I'll re-run the test checks!

I hope that will solve the problem!

**Comment by aazuspan** [comment]
Hi @davemlz, I've added the refresh token to my fork. Hopefully that fixes the issue!

**Comment by davemlz** [comment]
Hi, @aazuspan!

I don't know why the checks are not working yet. Let me check if I can find the problem. If not, I will clone your fork and run the tests from local to see what's happening. I'll let you know!

**Comment by aazuspan** [comment]
Sounds good, let me know if there's anything I can do on my end!

**Comment by davemlz** [comment]
Hi, @aazuspan!

I've tried your fork in local and the tests are in perfect conditions! I still don't know why the checks are not working, so, let's do this: Since the tests are perfectly working, I can merge the PR! :) Just some points:

- Please update the branch so it is even with the master branch.
- If you want, you can add some tutorials to the `tutorials` folder that is in the root. At the moment there are 22 tutorials, so, you can start from 23 and you can do as many as you want. This is just if you want :) If you do, please add your contact info at the beginning of the tutorials, something like:

*Tutorial created by:* [Aaron Zuspan](https://github.com/aazuspan)

I think that's all!

Let me know :)

**Comment by aazuspan** [comment]
Thanks @davemlz! I've updated and added a tutorial. Should be good to merge now if the tutorial looks okay!

**Comment by davemlz** [comment]
Hi, @aazuspan!

Everything was perfect and your branch has been merged!

Thank you very much for contributing to eemont!

**Pull request merged**
